# deploy-preprod.yml

# Étape de test pour l'environnement de pré-production
default: 
  tags:
    - rfw
stages:
  - test
  - deploy
  - publish



test-preprod:
  stage: test
  image: registry.gitlab.com/pfe8320617/pfe_test:robotframework
  script:
    - echo "Running tests for preprod environment..."
    - robot --variablefile ./environments/preprod.yml --listener reports/ListenerBase.py --outputdir reports Tests . || true

deploy-preprod:
  stage: deploy
  image: registry.gitlab.com/pfe8320617/pfe_test:robotframework
  script:
    - python3 send_email.py preprod
  only:
    - master